CREATE TYPE "public"."organization_role" AS ENUM('vendor', 'client');--> statement-breakpoint
CREATE TYPE "public"."relationship_status" AS ENUM('pending', 'active', 'terminated');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('admin', 'member');--> statement-breakpoint
CREATE TABLE "dashboard_widgets" (
	"widget_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dashboard_widgets_widget_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"dashboard_id" integer NOT NULL,
	"widget_type" varchar(50) NOT NULL,
	"created_by_user_id" integer NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"title" varchar(255),
	"is_visible_to_client" boolean DEFAULT true NOT NULL,
	"is_editable_by_client" boolean DEFAULT false NOT NULL,
	"is_layout_locked" boolean DEFAULT true NOT NULL,
	"grid_x" integer NOT NULL,
	"grid_y" integer NOT NULL,
	"grid_w" integer NOT NULL,
	"grid_h" integer NOT NULL,
	"min_w" integer,
	"min_h" integer,
	"max_w" integer,
	"max_h" integer,
	"client_grid_x" integer,
	"client_grid_y" integer,
	"client_grid_w" integer,
	"client_grid_h" integer,
	"config" jsonb DEFAULT '{}'::jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dashboards" (
	"dashboard_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dashboards_dashboard_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"relationship_id" integer NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "dashboards_relationship_id_unique" UNIQUE("relationship_id")
);
--> statement-breakpoint
CREATE TABLE "invitations" (
	"invitation_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "invitations_invitation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"org_id" integer NOT NULL,
	"email" varchar(255) NOT NULL,
	"role" "user_role" NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires_at" timestamp (6) with time zone NOT NULL,
	"accepted_at" timestamp (6) with time zone,
	"invited_by_user_id" integer,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "invitations_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "organization_roles" (
	"organization_id" integer NOT NULL,
	"role" "organization_role" NOT NULL,
	CONSTRAINT "organization_roles_organization_id_role_pk" PRIMARY KEY("organization_id","role")
);
--> statement-breakpoint
CREATE TABLE "organizations" (
	"organization_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organizations_organization_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "password_reset_tokens" (
	"token_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "password_reset_tokens_token_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"reset_token" varchar(255) NOT NULL,
	"expires_at" timestamp (6) with time zone NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"used_at" timestamp (6) with time zone,
	CONSTRAINT "password_reset_tokens_reset_token_unique" UNIQUE("reset_token")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"user_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organization_id" integer NOT NULL,
	"first_name" varchar(255) NOT NULL,
	"last_name" varchar(255) NOT NULL,
	"role" "user_role" NOT NULL,
	"email" varchar(255) NOT NULL,
	"password_hash" varchar(255) NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "vendor_client_relationships" (
	"relationship_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vendor_client_relationships_relationship_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vendor_org_id" integer NOT NULL,
	"client_org_id" integer NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"status" "relationship_status" DEFAULT 'pending' NOT NULL,
	CONSTRAINT "vendor_client_relationships_vendor_org_id_client_org_id_unique" UNIQUE("vendor_org_id","client_org_id")
);
--> statement-breakpoint
CREATE TABLE "widget_templates" (
	"template_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "widget_templates_template_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"owner_org_id" integer NOT NULL,
	"widget_type" varchar(50) NOT NULL,
	"title" varchar(255),
	"config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by_user_id" integer,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "dashboard_widgets" ADD CONSTRAINT "dashboard_widgets_dashboard_id_dashboards_dashboard_id_fk" FOREIGN KEY ("dashboard_id") REFERENCES "public"."dashboards"("dashboard_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dashboard_widgets" ADD CONSTRAINT "dashboard_widgets_created_by_user_id_users_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("user_id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "dashboards" ADD CONSTRAINT "dashboards_relationship_id_vendor_client_relationships_relationship_id_fk" FOREIGN KEY ("relationship_id") REFERENCES "public"."vendor_client_relationships"("relationship_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_org_id_organizations_organization_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("organization_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_invited_by_user_id_users_user_id_fk" FOREIGN KEY ("invited_by_user_id") REFERENCES "public"."users"("user_id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "organization_roles" ADD CONSTRAINT "organization_roles_organization_id_organizations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_organization_id_organizations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "vendor_client_relationships" ADD CONSTRAINT "vendor_client_relationships_vendor_org_id_organizations_organization_id_fk" FOREIGN KEY ("vendor_org_id") REFERENCES "public"."organizations"("organization_id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "vendor_client_relationships" ADD CONSTRAINT "vendor_client_relationships_client_org_id_organizations_organization_id_fk" FOREIGN KEY ("client_org_id") REFERENCES "public"."organizations"("organization_id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "widget_templates" ADD CONSTRAINT "widget_templates_owner_org_id_organizations_organization_id_fk" FOREIGN KEY ("owner_org_id") REFERENCES "public"."organizations"("organization_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "widget_templates" ADD CONSTRAINT "widget_templates_created_by_user_id_users_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("user_id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "dashboard_widgets_dashboard_id_idx" ON "dashboard_widgets" USING btree ("dashboard_id");--> statement-breakpoint
CREATE INDEX "dashboard_widgets_created_by_user_id_idx" ON "dashboard_widgets" USING btree ("created_by_user_id");--> statement-breakpoint
CREATE INDEX "invitations_org_id_idx" ON "invitations" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "invitations_invited_by_user_id_idx" ON "invitations" USING btree ("invited_by_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "unique_pending_invitation" ON "invitations" USING btree ("org_id","email") WHERE "invitations"."accepted_at" is null;--> statement-breakpoint
CREATE INDEX "password_reset_tokens_user_id_idx" ON "password_reset_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "users_org_id_idx" ON "users" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "vcr_vendor_org_id_idx" ON "vendor_client_relationships" USING btree ("vendor_org_id");--> statement-breakpoint
CREATE INDEX "vcr_client_org_id_idx" ON "vendor_client_relationships" USING btree ("client_org_id");--> statement-breakpoint
CREATE INDEX "widget_templates_owner_org_id_idx" ON "widget_templates" USING btree ("owner_org_id");--> statement-breakpoint
CREATE INDEX "widget_templates_created_by_user_id_idx" ON "widget_templates" USING btree ("created_by_user_id");